# Generated by Django 4.2.10 on 2024-02-12 04:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('sku', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('inStock', models.PositiveBigIntegerField()),
                ('availableStock', models.PositiveBigIntegerField()),
                ('tag1', models.BooleanField(default=False)),
                ('tag2', models.BooleanField(default=False)),
                ('tag3', models.BooleanField(default=False)),
                ('tag4', models.BooleanField(default=False)),
                ('tag5', models.BooleanField(default=False)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='api.category')),
            ],
        ),
    ]
